In [1]:
import pandas as pd

In [2]:
# import data
df = pd.read_csv("vine_table.csv")
df

,review_id,star_rating,helpful_votes,total_votes,vine,verified_purchase
0,RMDCHWD0Y5OZ9,3.0,0.0,1.0,N,N
1,RZSL0BALIYUNU,5.0,0.0,0.0,N,Y
2,RIZR67JKUDBI0,3.0,0.0,1.0,N,Y
3,R27HL570VNL85F,5.0,0.0,0.0,N,Y
4,R34EBU9QDWJ1GD,5.0,0.0,0.0,N,Y
...,...,...,...,...,...,...
904760,R6MDTUK723YPY,4.0,143.0,148.0,N,N
904761,R10B4417NCK98O,5.0,24.0,24.0,N,N
904762,R3V2A0GUZ3JAQ4,4.0,27.0,29.0,N,N
904763,R1VYXC7FFG4LGH,4.0,46.0,49.0,N,N
904764,R2XJJXFZOM36V5,5.0,17.0,19.0,N,N

In [3]:
# filter by more than 20 total votes
lotta_votes_df = df.query('total_votes >= 20') 
lotta_votes_df

,review_id,star_rating,helpful_votes,total_votes,vine,verified_purchase
28,R2243Y3OD8U6KQ,5.0,47.0,61.0,N,N
85,R2TGT0CDTCAAHW,5.0,21.0,23.0,N,Y
457,RX4D22YSXEF4P,1.0,37.0,38.0,N,Y
1028,R3FL2NTLFUSPTQ,5.0,33.0,37.0,N,N
1039,R3QTP3YNZXAPPF,3.0,23.0,24.0,N,Y
...,...,...,...,...,...,...
904759,R2EJ952S3YK254,4.0,46.0,47.0,N,N
904760,R6MDTUK723YPY,4.0,143.0,148.0,N,N
904761,R10B4417NCK98O,5.0,24.0,24.0,N,N
904762,R3V2A0GUZ3JAQ4,4.0,27.0,29.0,N,N
904763,R1VYXC7FFG4LGH,4.0,46.0,49.0,N,N

In [4]:
# filter again by helpfulness
helpful_votes_df = lotta_votes_df.query('helpful_votes/total_votes >= 0.5')
helpful_votes_df

,review_id,star_rating,helpful_votes,total_votes,vine,verified_purchase
28,R2243Y3OD8U6KQ,5.0,47.0,61.0,N,N
85,R2TGT0CDTCAAHW,5.0,21.0,23.0,N,Y
457,RX4D22YSXEF4P,1.0,37.0,38.0,N,Y
1028,R3FL2NTLFUSPTQ,5.0,33.0,37.0,N,N
1039,R3QTP3YNZXAPPF,3.0,23.0,24.0,N,Y
...,...,...,...,...,...,...
904759,R2EJ952S3YK254,4.0,46.0,47.0,N,N
904760,R6MDTUK723YPY,4.0,143.0,148.0,N,N
904761,R10B4417NCK98O,5.0,24.0,24.0,N,N
904762,R3V2A0GUZ3JAQ4,4.0,27.0,29.0,N,N
904763,R1VYXC7FFG4LGH,4.0,46.0,49.0,N,N

In [5]:
# filter again for reviews left by vine = y
vine_yes_df = helpful_votes_df.query('vine == "Y"')
vine_yes_df

,review_id,star_rating,helpful_votes,total_votes,vine,verified_purchase
4229,R1R9RU7JW0MFR2,4.0,20.0,23.0,Y,N
9120,R19EFYNN3W8Q07,5.0,26.0,32.0,Y,N
34704,R34DJ1R8AEU0SG,5.0,29.0,35.0,Y,N
38510,R25P5CXK5L9RHF,5.0,146.0,161.0,Y,N
49330,R2E9VZB3I4LSN5,5.0,55.0,59.0,Y,N
73488,RKYLHZL7EPELX,4.0,19.0,25.0,Y,N
177563,R1U13EKGQD3ZE6,5.0,22.0,25.0,Y,N
190962,RYW05F1MUEF01,5.0,87.0,102.0,Y,N
227822,R2SW4NXNO7HZJ5,4.0,28.0,33.0,Y,N
237635,R2016NFLSUR97Y,2.0,26.0,37.0,Y,N
307453,RFCV9QXJ3D79X,3.0,20.0,22.0,Y,N
312863,R36779ZAY4ZT0Y,3.0,46.0,50.0,Y,N
316563,R13PPTBWWV10Q6,5.0,19.0,25.0,Y,N
357373,R2A3FFNJTDUBMV,5.0,20.0,27.0,Y,N
366816,R3QQG4HUB214TM,5.0,111.0,128.0,Y,N
366973,R3J9OSJNJB7KGM,5.0,70.0,80.0,Y,N
367038,RIMYDUAAFXY2U,5.0,22.0,23.0,Y,N
394836,R22CYBPLKWDK6F,5.0,47.0,54.0,Y,N
400167,R1ETBDZ1LJ8CEL,4.0,28.0,32.0,Y,N
403075,R28T5ISQ8AA7E5,5.0,40.0,42.0,Y,N
423840,R1OIXASHDMAU84,5.0,35.0,40.0,Y,N
425838,R2XBIPOLCU015D,4.0,23.0,28.0,Y,N
428102,R30FS6HFPQ1WKT,5.0,41.0,44.0,Y,N
436145,R6BXKPVUVXBTT,4.0,43.0,47.0,Y,N
440256,RX4P0ENQPW8JW,3.0,20.0,24.0,Y,N
443846,R33G6UUWX1SZ1W,4.0,36.0,41.0,Y,N
447381,R3NGT6QJHCUOKV,4.0,34.0,38.0,Y,N
492630,R4KIRC319GP61,5.0,19.0,23.0,Y,N
495259,R1UZW5KV87WUA1,5.0,26.0,30.0,Y,N
497969,R1I98OVWL8N0X,3.0,16.0,28.0,Y,N
508562,R113X83B4OZYF8,3.0,37.0,47.0,Y,N
509123,R394FJYWZ0GNFG,5.0,40.0,43.0,Y,N
510047,R3QE0Q8R65G2M9,5.0,52.0,56.0,Y,N
513953,RARYFB85E8YSK,5.0,25.0,31.0,Y,N
519257,R295FZN1I3KSQM,5.0,71.0,75.0,Y,N
522139,R2VRYZV3N49TJ0,4.0,29.0,33.0,Y,N
537659,R27L14PCLC87MI,5.0,70.0,73.0,Y,N
544991,R6PO4CRQ8RWVP,4.0,34.0,36.0,Y,N
559334,RP24DFOZY82Z9,5.0,24.0,26.0,Y,N
559377,R2CCHT4ZV5ZM5X,4.0,22.0,25.0,Y,N
577368,R2UP2773CHKTE3,5.0,71.0,76.0,Y,N
594070,R1HZ9P5BJJZWNU,3.0,61.0,68.0,Y,N
596862,R35BSD0RCM94I2,3.0,128.0,145.0,Y,N
635654,R2ZVYKSW84Z47N,5.0,67.0,70.0,Y,N
637573,R2Q5W1NNKF8ESR,5.0,20.0,24.0,Y,N
640709,R1YGI7SDJBIITA,3.0,67.0,77.0,Y,N
641839,R2UJHZ50AMCITI,5.0,22.0,22.0,Y,N
641917,R3VHUT5HS9V22R,4.0,19.0,24.0,Y,N
644593,R25AJSJ49JA89T,5.0,61.0,63.0,Y,N
652098,R1WYQYB9KX1WM1,5.0,32.0,36.0,Y,N
658817,ROIU1G8UOP20L,3.0,14.0,22.0,Y,N
680512,R2ID3IBRNPEAKZ,5.0,42.0,46.0,Y,N
736368,R1LLUVTO5GEFHS,4.0,40.0,41.0,Y,N
742766,RAGY9ISHYAS08,4.0,19.0,22.0,Y,N
759938,R3HCAEISSZTOPF,5.0,47.0,57.0,Y,N
761174,RMCGLOIUS31A0,5.0,22.0,30.0,Y,N
766961,R2XWB7UZBANOS3,4.0,18.0,20.0,Y,N
816778,R2YI9KHLBCF0NF,5.0,34.0,45.0,Y,N
816859,R2HT2LBF48R9HC,5.0,26.0,38.0,Y,N
820981,R3Q3WCJO38879H,4.0,25.0,25.0,Y,N

In [6]:
# filter again for reviews left by vine = n
vine_no_df = helpful_votes_df.query('vine == "N"')
vine_no_df

,review_id,star_rating,helpful_votes,total_votes,vine,verified_purchase
28,R2243Y3OD8U6KQ,5.0,47.0,61.0,N,N
85,R2TGT0CDTCAAHW,5.0,21.0,23.0,N,Y
457,RX4D22YSXEF4P,1.0,37.0,38.0,N,Y
1028,R3FL2NTLFUSPTQ,5.0,33.0,37.0,N,N
1039,R3QTP3YNZXAPPF,3.0,23.0,24.0,N,Y
...,...,...,...,...,...,...
904759,R2EJ952S3YK254,4.0,46.0,47.0,N,N
904760,R6MDTUK723YPY,4.0,143.0,148.0,N,N
904761,R10B4417NCK98O,5.0,24.0,24.0,N,N
904762,R3V2A0GUZ3JAQ4,4.0,27.0,29.0,N,N
904763,R1VYXC7FFG4LGH,4.0,46.0,49.0,N,N

In [7]:
# find total number of reviews for vine=y & vine=n
total_reviews_yes = pd.Series(vine_yes_df['review_id']).count()
print(f'yes = {total_reviews_yes}')

total_reviews_no = pd.Series(vine_no_df['review_id']).count()
print(f'no = {total_reviews_no}')

yes = 60
no = 14477

In [8]:
# find number of 5-star reviews for vine=y & vine=n
five_star_yes = vine_yes_df.query('star_rating == 5.0')
five_star_yes_num = pd.Series(five_star_yes['review_id']).count()
print(f'yes = {five_star_yes_num}')

five_star_no = vine_no_df.query('star_rating == 5.0')
five_star_no_num = pd.Series(five_star_no['review_id']).count()
print(f'no = {five_star_no_num}')

yes = 34
no = 8212

In [9]:
# the percentage of 5-star reviews for vine=y(paid) & vine=n(unpaid)
yes_percentage = (five_star_yes_num / total_reviews_yes)
print(f'yes = {yes_percentage:.2%}')

no_percentage = (five_star_no_num / total_reviews_no)
print(f'no = {no_percentage:.2%}')

yes = 56.67%
no = 56.72%